### PR TITLE
add contributors list

### PR DESCRIPTION
**Pull request by mukuvi**
add contributors list

### CODE REVIEW

**Review by kabugatti — COMMENTED** [review]
- First of all, wrong spelling of my name. There's a K at the end.

- Second, the contributor's list has already been added and submitted.

**Comment by Itsfoss0** [comment]
> * First of all, wrong spelling of my name. There's a K at the end.
> * Second, the contributor's list has already been added and submitted.

Ouch !! 😢

**Comment by kabugatti** [comment]
> > * First of all, wrong spelling of my name. There's a K at the end.
> > * Second, the contributor's list has already been added and submitted.
> 
> Ouch !! 😢

Vawulence wakes people up @Itsfoss0, but I digress, @jmngandu can have his changes approved if he just adds his name in the [contributor's list](https://github.com/grand-rick001/luna-hacks-projects/blob/master/CONTRIBUTORS.md) while at the same time retaining the format.

**Comment by mukuvi** [comment]
😂😂

**Comment by mukuvi** [comment]
Nice!

**Comment by mukuvi** [comment]
hii multmedia inahusu nini, unaeza nitumia screen shot ya layout

**Pull request closed without merging**
